FROM  zhoulouzi/centos:7.6-base

LABEL maintainer="zhouzichen@hotmail.com"

ENV NODE_VERSION 10.15.0
ADD node-v10.15.0-linux-x64.tar.xz /apps/nodejs/

ENV NODEJS_HOME /apps/nodejs/node-v10.15.0-linux-x64
ENV PATH $NODEJS_HOME/bin:$PATH
